input1=input("Enter your first input=")
input2=input("Enter your second input=")
a1= int(input1) + int(input2)
a2= int(input1) - int(input2)
a3= int(input1) * int(input2)
a4= int(input1) / int(input2)
print("Sum= %d, Subtraction=%d, Multiplicaation= %d, Division= %d " % (a1, a2, a3, a4))